{:prod {:env {:java-loaded "confirm"
       :log-dir "/home/ubuntu/server/logs/"
       :ssl-dir "/home/ubuntu/server/ssl/"
       :app-domain "https://www.candlecrm.com"
       :database-url "bolt://localhost"
       :database-username "neo4j"
       :database-password "josedog"
       :coreference "false"
       :train-user "trainuser@foobar.com"
       :geocode-api-key " "
       :google-client-id " "
       :google-client-secret " "
       :test-acct-email "alyssamvance@gmail.com"
       :test-acct-pwd "dummy271"
       :neo4j-browser "http://localhost:7474/browser/"
       :sendgrid-api " "
       :log-file "general_log.txt"
       :privkey-pwd " "
       :cypher-log-file "cypher_log.txt"
       :recon-log-file "recon_log.txt"
       :firefox-profile "/home/alyssa/.mozilla/firefox/je0kknm8.default"
       :gmaps-api-key " "
       :in-dev "false"}}}
